/* https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAttestationResponse */

using System;

namespace Indice.AspNetCore.Fido.Models
{
    /// <summary>
    /// Describes a cryptographic root of trust for the key pair that has been generated by the client.
    /// </summary>
    public class AuthenticatorAttestationResponse
    {
        public AuthenticatorAttestationResponse(string clientDataJson, string attestationObject) {
            ClientDataJson = Convert.FromBase64String(clientDataJson);
            AttestationObject = Convert.FromBase64String(attestationObject);
        }

        /// <summary>
        /// Client data for the authentication, such as origin and challenge.
        /// </summary>
        public byte[] ClientDataJson { get; set; }
        /// <summary>
        /// Contains the public key, as well as signature over the entire attestation object with a private key that is stored in the authenticator when it is manufactured.
        /// </summary>
        public byte[] AttestationObject { get; set; }
    }

    /// <summary>
    /// Describes a cryptographic root of trust for the key pair that has been generated by the client.
    /// </summary>
    public class AuthenticatorAttestationResponseBase64
    {
        /// <summary>
        /// Client data for the authentication, such as origin and challenge.
        /// </summary>
        public string ClientDataJson { get; set; }
        /// <summary>
        /// Contains the public key, as well as signature over the entire attestation object with a private key that is stored in the authenticator when it is manufactured.
        /// </summary>
        /// <remarks>https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAttestationResponse/attestationObject</remarks>
        public string AttestationObject { get; set; }
    }
}
