/* 
 * https://www.w3.org/TR/webauthn/#authenticatorattestationresponse
 * https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential
 */

using System;

namespace Indice.AspNetCore.Fido.Models
{
    /// <summary>
    /// Provides information about a public key/private key pair, which is a credential for registering/logging in to a service using an asymmetric key pair.
    /// </summary>
    public class PublicKeyCredential
    {
        /// <summary>
        /// Creates a new instance of <see cref="PublicKeyCredential"/>.
        /// </summary>
        /// <param name="id">The id read-only property of the public key credential, which acts as the identifier. This is a base64 URL encoded version of the rawId.</param>
        /// <param name="rawId">The rawId read-only property of the public key credential containing the identifier of the credentials. This identifier is expected to be globally unique.</param>
        /// <param name="type">Always set to 'public-key' for public key credential instances.</param>
        /// <param name="authenticatorAttestationResponse">Describes a cryptographic root of trust for the key pair that has been generated by the client.</param>
        public PublicKeyCredential(string id, string rawId, string type, AuthenticatorAttestationResponse authenticatorAttestationResponse) {
            Id = id ?? throw new ArgumentNullException(nameof(id));
            RawId = !string.IsNullOrWhiteSpace(rawId) ? Convert.FromBase64String(rawId) : throw new ArgumentNullException(nameof(rawId));
            Type = type ?? throw new ArgumentNullException(nameof(type));
        }

        /// <summary>
        /// The id read-only property of the public key credential, which acts as the identifier. This is a base64 URL encoded version of the <see cref="RawId"/>.
        /// </summary>
        public string Id { get; }
        /// <summary>
        /// The rawId read-only property of the public key credential containing the identifier of the credentials. This identifier is expected to be globally unique.
        /// </summary>
        public byte[] RawId { get; }
        /// <summary>
        /// Always set to 'public-key' for public key credential instances.
        /// </summary>
        public string Type { get; }
        /// <summary>
        /// Describes a cryptographic root of trust for the key pair that has been generated by the client.
        /// </summary>
        public AuthenticatorAttestationResponse AuthenticatorAttestationResponse { get; }
    }

    /// <summary>
    /// Provides information about a public key/private key pair, which is a credential for registering/logging in to a service using an asymmetric key pair.
    /// </summary>
    public class IPublicKeyCredentialBase64
    {
        /// <summary>
        /// The id read-only property of the public key credential, which acts as the identifier. This is a base64 URL encoded version of the <see cref="RawId"/>.
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// The rawId read-only property of the public key credential containing the identifier of the credentials. This identifier is expected to be globally unique.
        /// </summary>
        public string RawId { get; set; }
        /// <summary>
        /// Always set to 'public-key' for public key credential instances.
        /// </summary>
        public string Type { get; set; }
        /// <summary>
        /// Describes a cryptographic root of trust for the key pair that has been generated by the client.
        /// </summary>
        public AuthenticatorAttestationResponseBase64 AuthenticatorAttestationResponseBase64 { get; set; }
    }

    /// <summary>
    /// Extension methods on type <see cref="IPublicKeyCredentialBase64"/>.
    /// </summary>
    public static class IPublicKeyCredentialBase64Extensions
    {
        /// <summary>
        /// Converts an implementation of <see cref="IPublicKeyCredentialBase64"/> to a <see cref="PublicKeyCredential"/> object.
        /// </summary>
        /// <param name="response">Provides information about a public key/private key pair, which is a credential for registering/logging in to a service using an asymmetric key pair.</param>
        public static PublicKeyCredential ToPublicKeyCredential(this IPublicKeyCredentialBase64 response) {
            var authenticatorAttestationResponse = new AuthenticatorAttestationResponse(response.AuthenticatorAttestationResponseBase64.ClientDataJson, response.AuthenticatorAttestationResponseBase64.AttestationObject);
            return new(response.Id, response.RawId, response.Type, authenticatorAttestationResponse);
        }
    }
}
